### ISSUE TITLE
Add support for languages that don't use white-spaces (normally)

### ISSUE THREAD

**Issue by otacke** [otacke/h5p-dictation#31]
Some languages such as Chinese normally don't use white spaces, but given the unicode character range, han characters could be split automatically. Real word splitting would require a special dictionary/grammar library to identify groups of han characters as words.

**Comment by rolandsherwood3** [comment]
Hello. First, please allow me to say a very quick, very big thank you for all your contributions to the H5P community - including the Dictation content type!

Second, my organization is currently implementing H5P but has encountered an issue with the Dictation content type which is causing us some confusion. Basically, our Japanese language department are attempting to use the Dictation content type to test students' comprehension of spoken Japanese sentences. However, the way the Dictation content type scores attempts - specifically, how and why certain combinations of Japanese characters are recognized as correct - is unclear to us.

We have made sure the 'Splitting of characters' option is enabled. However, when submitting and checking an attempt, for some reason certain characters are treated individually, while others are combined together into a larger group:

<img width="999" alt="Screenshot 2024-05-22 at 17 33 01" src="https://github.com/otacke/h5p-dictation/assets/169862467/22e431a3-37d9-405d-bc37-4bfd9f495bd8">

This is not a problem if the student enters the exact, correct answer. However, if a student enters only some of the words in the sentence, they may not be recognized correctly and therefore marked as incorrect. For example, in the above screenshot, the first 3 characters entered (富士山) actually constitute a single word (Mt. Fuji). If a student enters only these 3 characters, though, they will not be recognized as a single word. In fact, the last character will be marked as incorrect because the Dictation content type thinks it should belong to a longer string of characters (which, itself, actually contains several other words):

<img width="1003" alt="Screenshot 2024-05-22 at 17 36 14" src="https://github.com/otacke/h5p-dictation/assets/169862467/adedad10-7a5f-4353-8842-b52ca967defe">

If you can provide any insight or suggestions regarding this issue we would be very grateful. We would like to use the Dictation type extensively across our Japanese and other language programs; However, at the moment, it does not appear this will be possible if scoring is not accurate.

Thank you again!

**Comment by otacke** [comment]
The automated splitting requires to explicitly know what characters should be split. In your example, I see a kanji (yama/san) followed by a hiragana character (ga) and that followed by some katakana characters. You can easily spot that a space will only be added automatically when there are two consecutive kanji.

Hiragana and katakana were simply not declared as characters entitled for being split automatically.

I changed that and just released an update to 1.3.3. Please note that I cannot tell when an update gets released by H5P Group on the H5P Hub. That's up to them.

If you want to install the update, please go to https://www.olivertacke.de/labs/2018/01/07/not-done-yet-but-what-do-you-think-about-h5p-dictation/ and download the demo content. Then install it onto your platform with administrative rights. That will not only upload the demo content, but also install the new library.

**Comment by rolandsherwood3** [comment]
Hello Oliver. Thank you very much for your kind assistance! We really are grateful as well as happy it was something that was easy to fix.

Unfortunately, we are using H5P.com and so can't immediately make use of the 1.3.3 update. However, I will discuss with customer support their ability for them to update to this new version asap.

Again, thank you very much!

**Comment by otacke** [comment]
@rolandsherwood3 I already created a ticket for H5P Group yesterday (https://h5ptechnology.atlassian.net/browse/HFP-3951). Feel free to reference it (code HFP-3951) when reaching out to H5P Group. Their product owner will know what to do.

**Comment by rolandsherwood3** [comment]
Apologies for the late reply Oliver - and sincere thanks again! I have now contacted H5P Group and am waiting to hear more regarding integration.
