### ISSUE TITLE
Apostrophe in french is not correctly handled

### ISSUE THREAD

**Issue by isa-realia** [otacke/h5p-dictation#52]
Hello !

I am using Dictation as a wordpress plugin. The apostrophes are not correctly handled : they are considered as errors because the displayed character doesn't match the "curly" apostrophe (see attached screenshot). When "Ignore Punctuation marks" is checked in "Behavioural settings", apostrophes are still handled as errors.

![Capture d’écran 2020-09-12 à 14 51 14](https://user-images.githubusercontent.com/18722367/92996016-8cdc1b00-f508-11ea-81e1-f826bac7eb74.png)

Thanks,

Isabelle

**Comment by isa-realia** [comment]
Fixed : the apostrophes were not handled because I used copy-pasted sentences when editing my content of dictation. I have re-edited all apostrophes and replaced them with straight / single quote and they are now correctly handled. I just have to keep that in mind when I copy-paste my content.
Thanks,
Isabelle

**Comment by otacke** [comment]
@isa-realia Apostrophes are annoying, because there are too many of them ... If you use the regular apostrophe, Dictation already handles input that depending on the device may be a regular apostrophe or a _left single quotation mark_. There's a standardized way to do that. But if you explicitly use one of the _single quotation marks_ as the solution (by copy and paste), then yes, there will be trouble as the regular apostrophe will be considered a mistake.

I could, of course, simply treat the apostrophe, the left single quotation mark and the right single quotation mark (or whatever might look similar) as just one character, but then someone will ask why an apostrophe will be considered as correct if he/she explicitly wanted e.g. a left single quotation mark ...

**Comment by isa-realia** [comment]
Thanks for the explanation ! Apostrophes are annoying indeed... We just have to keep that in mind when we copy-paste and to replace whatever "pasted fancy apostrophes / quotation marks" by regular apostrophes. Simple and universal fix ;)
