### ISSUE TITLE
Implement a case sensitive checkbox option

### ISSUE THREAD

**Issue by clonecorp** [otacke/h5p-dictation#55]
Hello,

I really like H5P and have been using pretty much every module. This one unfortunately doesn't include a case sensitive option if order to accept solutions like : "Hello", "HELLO", "hello" as good answers. I use for now the vertical line (|) to input those options, but it's impossible for long sentences to do that. Would that be something you could implement? I know it's present in the "Fill in the blanks" module which works great.

**-----------**
**EDIT : I just noticed in the closed issues that people mentioned it so you can igore that part**
Also, I noticed something weird but interesting at the same time. I typed the sentence "I don't eat chocolate" and the plugin corrected me with "I don’t eat chocolate". As you can see there are two different apostrophes (I didn't know that). I checked and saw that some apps like Word use the ’ (Typesetter's apostrophe) while most keyboards and phones use ' (Typewriter apostrophe) and while I was making the sentences in Word, I copied them over, tested them and then understood that the same would happen with the dashes - – — but unfortunately H5P doesn't consider them as punctuations so an error pops up when using the incorrect signs. That was my discovery, just wanted to let you know.
**-----------**

Lastly, if you know what I could use as a "popup" window for people to use specific character not present on the keyboard like "È, É, Ê, Ë, ..." let me know. I read on the H5P site that it'd be something a bit too hard to implement but if you know any good option I can use and that I can implement for inputing special characters, let me know.

Thank you for creating H5P!

**Comment by otacke** [comment]
@clonecorp 
It wouldn't be complicated to add such an "ignore case" option, but I try not to get in too many niche options. I believe most people want a dictation to be as correct as possible.

Regarding apostrophes/single quotation marks, please see https://github.com/otacke/h5p-dictation/issues/52#issuecomment-691489361

I'll have to check for the dashes. Those should count as punctuations, of course.

Such a keyboard isn't "hard" to implement, but it definitely doesn't make sense to build it into every single content type - possibly into H5P core - but then again, there are even browser plugins and ways on every major OS to type those characters.

**Comment by clonecorp** [comment]
@otacke yes it makes sense. I understand what you mean. I thought of the checkbox since it has been implemented in other modules and would be easy to add but I understand the purpose of the dictation module.

Regarding the dashes, yes. I'm pretty there are other stuff as well like the quotes " " “ ” « » or parenthesis ( ). I don't if they right are counted as punctuation characters because I haven't tested them but they should. So many characters in every language, it'd be hard to think of them all.

I'll see what I can find. The problem is that most users don't really use the keyboards in other languages. Or, if they use it, they use the regular letters and not the special characters, I'll see what I can find to make the user experience a bit more friendly.

**Comment by otacke** [comment]
@clonecorp I'll take a look at potential missing characters counting as punctuations. It's just a string to be amended at https://github.com/otacke/h5p-dictation/blob/master/src/scripts/h5p-dictation-sentence.js#L749

Regarding the keyboard: I understand the problem. My thought is that if you look at the "stack" of

operating system => browser => H5P core => H5P content types

(from a developer's perspective) it makes sense to have such a feature as low as possible, because all levels built on top can use it.

My Android phone for instance, allows to me easily add languages to my keyboard and use their special characters (I have German and Norwegian), layouts (I have Russian) or even special input modes (I have Japanese). I can use these a) everywhere in native apps and in browser apps like H5P and b) the keyboard is the same everywhere. That's why it's cool on that level - and I think all major operating systems support alternative keyboard layouts (at least my Linux does) or virtual keyboards.

If I built a keyboard into Dictation, it would only be usable in there - nah. But as I mentioned, I understand that especially language learning apps sort of need to have it, and it's more convenient to use.

So, if OS support and browser support is not an option, I'd vote for adding a virtual keyboard feature into the core of H5P (as it's supposed to be a framework developers can use). This way any content type could use it easily (good for developers), so it could be consistent across content types (good for users) and potentially reduce the amount of library storage needed (good for admins, although this is rather an academic argument ;-)).

So feel free to post your discussion/request at https://h5p.org/forum or, if you prefer github, at https://github.com/h5p/h5p-php-library

**Comment by otacke** [comment]
@clonecorp I have now amended the list of punctuation symbols, so the next update should run a little smoother in that regard. Feel free to close the issue if you think it's done.

**Comment by otacke** [comment]
@clonecorp Version 1.0.7 of Dictation has just been released on h5p.org and should be available in the H5P Hub shortly.

**Comment by clonecorp** [comment]
Thank you @otacke. I'll close the issue. Have a good week!
