### ISSUE TITLE
Allow to show solution on check

### ISSUE THREAD

**Issue by tdjac0bs** [otacke/h5p-dictation#72]
Hello, we're working in a new feature that's allowing the user to see the solution right after clicking the Check button ( without the need to click in "Show solution" ).

If we add it as an option ( with default false ), would it be acceptable to merge it?

The option name would be "Show solution on check" ( or other that you suggest ).

Thanks!

**Comment by otacke** [comment]
Hmm, I understand the intention. I am just a little worried because the behavioral settings is quite bulky already. These settings would need to be grouped sensibly, then I don't see a problem. That will, however, mean changing the data structure (so one needs to be careful to not wreck the translation files that depend on the structure), and one would also have to write an `upgrades.js` file that moves the parameters to their proper new location when someone updates the content type library (I did something similar in https://github.com/otacke/h5p-agamotto/blob/master/upgrades.js#L51-L90). Nothing wrong with that, just some work that'd have to be done, too. And someone would have to come up with 3 or maybe 4 group labels to put the settings into.

**Comment by tdjac0bs** [comment]
No problem in creating a upgrade settings code, thanks for pointing this out.

Grouping the options sensibly looks challenging for me, but I can think in a possible approach for this specific case.

We could create a new field with name "Solution display" with three possible options:
- Never ( equivalent to "enable show solution button" disabled )
- Automatically ( this new option )
- Button click ( equivalent to "enable show solution button" enabled )

What do you think?

**Comment by otacke** [comment]
I'll think about how to group the current options in sub categories. It's than just moving things in semantics.json around and then the same in the translation files.

I wouldn't want to have conflicting options (your 3rd option could contradict the "enable show solution button option"), so having the "Show solution on check" option (boolean) would be fine.

**Comment by tdjac0bs** [comment]
Nice, so if I understood you correctly, I can proceed implementing this "Show solution on check" and we'll group it later, right?

**Comment by otacke** [comment]
Yes, it doesn't matter in what order that's done.

**Comment by otacke** [comment]
Please put it under the "Enable show solution button" and make it conditional - only show it if the "Enable show solution button" is enabled. That's what the "ShowWhen" widget can be used for. Guess you can figure out how that works. For peeking: https://github.com/otacke/h5p-dictation/blob/master/semantics.json#L27-L35
